### ISSUE TITLE
Easy PR for Hacktoberfest!

### ISSUE THREAD

**Issue by Cutwell** [Cutwell/Hacktoberfest-Census#1167]
1. Fork this repository.

2. Add your name + profile link to the Census list in the README.md file like so..
```markdown
[Cutwell](https://github.com/Cutwell)
```

3. Make a Pull Request for an easy contribution towards #Hacktoberfest 2017!

**Comment by jidemusty** [comment]
done

**Comment by GautamMandsorwale** [comment]
Hey, @Cutwell 

Please approve this request [https://github.com/Cutwell/Hacktoberfest-Census/pull/1185]

I have Added GautamMandsorwale into Census List.

Thanks Again!

Gautam Mandsorwale

**Comment by Cutwell** [comment]
Thanks to all who participated! Happy #Hacktoberfest!
