### ISSUE TITLE
What a terrible idea

### ISSUE THREAD

**Issue by GantMan** [Cutwell/Hacktoberfest-Census#1514]
People love to gamify.   Does anyone think [this](https://github.com/Cutwell/Hacktoberfest-Census/pulls) is the proper spirit of what Digital Ocean wanted?

By making this repo, you've taken away from open source.

Sorry to sound rude, but it's a bad repo, and you should feel bad.

**Comment by Cutwell** [comment]
Your exactly right, this could be considered a way to gamify the system - however it also serves a purpose as a survey, if in a satirical way.
Closed due to irrelevance, thank you for your time.

**Comment by RWOverdijk** [comment]
I agree. This is a bad idea. It's taking away from a generous and good spirited initiative. Shaaaaaame. 

![](https://media.giphy.com/media/Ob7p7lDT99cd2/giphy.gif)

**Comment by rmevans9** [comment]
> You're exactly right, this could be **considered** a way to gamify the system

*Emphasis mine*

You say is could be considered a way to gamify the system... I think there is no consideration needed. That is exactly what this repo is. You literally call it out as an easy way to get a PR for Hacktoberfest in the readme. 

> A census of those participating in Hacktoberfest 2017 **(and an easy PR!)**

*Emphasis mine*

> however it also serves a purpose as a survey, if in a satirical way.

Trying to justify this garbage much? Please don't. Things like this are detrimental to good initiatives by good people and could cause such people to think twice about doing it again in the future.

**Comment by Cutwell** [comment]
this issue was closed. therefore extended comments are neither appropriate nor appreciated, and as such have been deleted. Lets try to be civil now.
