### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by Cutwell** [Cutwell/Hacktoberfest-Census#1683]
Hi All,
I mentioned before that I'm happy to maintain this repo (i.e.: accept PR's) myself, however I didn't anticipate this level of involvement (over 1200 PR's at time of writing).
Hacktoberfest is pretty much over, but if anyone would be interested in accepting a few Pull Requests I'd be happy to grant permissions.
Cheers, Cutwell

**Comment by vrajroham** [comment]
I would help you!

**Comment by platy11** [comment]
@Cutwell I'm happy to help

**Comment by Cutwell** [comment]
@vrajroham @platy11, you've both been added - thanks for the help!

**Comment by vrajroham** [comment]
@Cutwell It's going tobe hard to merge the PR by multiple collaborators. I started merging from last PR. (Means who opened first) As I resolve conflict other conflict occurs for same PR and goes on. Because maybe other user had written on same line or other contents are there already.

**Comment by Cutwell** [comment]
@vrajroham I agree, I've looked into some form of automation - i.e.: comparing the main branch and PR for differences, then adding the differences to the main branch, but automating with Git is annoying

**Comment by christianheinrichs** [comment]
@Cutwell I would like to help out!

**Comment by shreyanshdwivedi** [comment]
@Cutwell I would like to help

**Comment by MichaelDeBoey** [comment]
If help is still needed, I'm in for it 🙂

**Comment by Cutwell** [comment]
@MichaelDeBoey @shreyanshdwivedi @christianheinrichs thanks for the offer! All added as collaborators.

**Comment by platy11** [comment]
@Cutwell How do you want to go about merging the PRs? Because now each PR wants to add the whole census to `README.md` again. What I did with some PRs was fix the merge conflict so the new name was added to the README, and then I made a commit copy/pasting them to the `2017.md` file.

**Comment by m1guelpf** [comment]
@Cutwell If you still need help, count me in!

**Comment by MichaelDeBoey** [comment]
@Cutwell Like @platy11 said, it's maybe a good thing to tell us how you would like that we work this out for you. 🙂

**Comment by Cutwell** [comment]
Hmm, my bad there. The easiest method may be to re-add the entire census to readme.md then move it to a seperate file at a future point.

**Comment by christianheinrichs** [comment]
@Cutwell Thanks for adding me to the collaborators.

Most of the PR merge conflicts could be resolved fairly easily via the web interface. However, for some reason an entry sometimes gets removed which then has to be re-added manually and I don't exactly know why, since this is the first time I'm merging pull requests on GitHub.

This happened in the commits 76f5fdecf2df8d0dcc7c78ab41b1c12a5d7ed6d2, c9f6c24b48a855d162aac0602d23047392c5d746 and 8cdf80ff433a0c2a2e40a89fa90898495fe026fb.

If anyone can help out with this, please post in this thread.

**Comment by Cutwell** [comment]
@christianheinrichs  Mind posting a screenshot to show what you mean?

**Comment by ajesusflores** [comment]
I manually resolved conflicts for my PR: https://github.com/Cutwell/Hacktoberfest-Census/pull/1089

**Comment by platy11** [comment]
@ajesusflores Thanks, I've merged it now. :+1:

**Comment by danedavid** [comment]
I have resolved conflicts in my PR too, if that helps https://github.com/Cutwell/Hacktoberfest-Census/pull/966/ :+1:  If you need further help, count me in.

**Comment by spences10** [comment]
Hey @Cutwell you still need help with this?

Everyone seems to have quietened down and there's still a good 1k PRs to merge, fi you want to add me as a contributor I'll tackle some of them 👍
