### ISSUE TITLE
Hacktoberfest 2018

### ISSUE THREAD

**Issue by Cutwell** [Cutwell/Hacktoberfest-Census#1818]
Hi All, old or new Hacktoberfest contributors!

This repository was initially created for the 2017 Hacktoberfest as a half joke, half serious census.
Given that I've seen over a hundred new pull requests in the last 2 days alone, I guess you guys want to use it this year as well!

So, to all of you who want to contribute to this project...

1. Fork this repository
2. Add your name and a link to your user profile like so:
`[Cutwell](https://github.com/Cutwell)`

3. Profit? Until I get around to implementing a bot, don't expect the census to be updated in any meaningful way. However a PR doesn't need to be accepted to count for Hacktoberfest so thats fine.

I would encourage everyone who participates in this project to not count it as one of your five Open Source contributions, due to it's simplistic nature, although obviously I can't stop you.

Have a great Hacktoberfest ya'll and happy hacking!

- Cutwell, 2018

**Comment by Arisdolanan** [comment]
update sensus for happy hacktoberfest 2018 #2012

**Comment by Arisdolanan** [comment]
#2012

**Comment by Arisdolanan** [comment]
update sensus for happy hacktoberfest 2018  #2012

**Comment by fineanmol** [comment]
Just Check this Repo Also of Hacktober Fest to win T-shirt ..        [Repo Hacktoberfest2k18](https://github.com/fineanmol/Hacktoberfest2k18)
