### ISSUE TITLE
Improve UI & make it responsive

### ISSUE THREAD

**Issue by merzak7** [Cutwell/Hacktoberfest-Census#323]
The website is not responsive ! 

![ScreenShot](https://screenshots.firefoxusercontent.com/images/9f7a62cc-909e-4280-8710-d5991cebd3de.png)

If you open this website on mobile you will see that layout is not particularly mobile friendly. The widths needs correcting,...

**Comment by IOAyman** [comment]
Agree!

**Comment by maryna-yanul** [comment]
Fixed by
https://github.com/Cutwell/Hacktoberfest-Census/pull/327
Please check :)

**Comment by merzak7** [comment]
Good work @maryna-yanul :+1: I hope @Cutwell will merge it :wink:

**Comment by Cutwell** [comment]
getting round to it, should be merged asap

**Comment by thatguywiththatname** [comment]
https://github.com/Cutwell/Hacktoberfest-Census/pull/327 has been merged
