### ISSUE TITLE
Changing the background color

### ISSUE THREAD

**Issue by shivanidotcom** [Cutwell/Hacktoberfest-Census#3302]
I would like to change the background color

**Comment by imNilabja** [comment]
I would like to do this task, could you please assign me.

**Comment by lubakdevkota** [comment]
assign me

**Comment by Manaswini123456** [comment]
Assign me please

**Comment by psantosh16** [comment]
Hi , would you like to assign this project to me , as I have experience in web dev past 2 years . So , I can help you with that. @shivanidotcom

**Comment by Sahilsin08** [comment]
Hi @shivanidotcom. I would like to be assigned in this project. As i have experience on this domain and need to gain more experience. So, please assign me on  this project. I will be thankful to you for this.

**Comment by psantosh16** [comment]
> Hello sir, Just wanted to know that do we need to change image background color or only the background color?

Background color.

**Comment by HaydenCour** [comment]
Hi, Could i be assigned to the project as well? Im learning how to use GitHub!

**Comment by bristi07** [comment]
Hello !!
I am new can you  please assign this task to me

**Comment by Rehanpasha732** [comment]
hey , i want to get started with the hacktoberfest , i am new to open source , please assign me this issue

**Comment by milanbhandari047** [comment]
Can you assign this to me?

**Comment by Ayushitgithub** [comment]
assign me this sirrrr please i am interested to work on this please i want to contribute i want to learn something

**Comment by 022003harsh** [comment]
i can do it please assign it to me you wont regret giving the project to me .

**Comment by arpanbiki** [comment]
Please assign this to me sir

**Comment by codingday123** [comment]
Assign me please

**Comment by helperBob** [comment]
Should be easily done with 
(Example code written in a css file)
`backgroundName {
  background-color: _red_;
}`

**Comment by kapiljain15778** [comment]
hey please assign this to me

**Comment by AnshikaVerma23** [comment]
@shivanidotcom, Can you give me a chance to work on this issue, I will be grateful to you .

**Comment by KaashviR** [comment]
Can you assign me this issue?

**Comment by pragyan4261** [comment]
Can you please assign me this issue?

**Comment by rajneesh-18** [comment]
Why no one is assigning the issue?
