### ISSUE TITLE
Light mode and dark mode feature enable

### ISSUE THREAD

**Issue by RitikJha93** [Cutwell/Hacktoberfest-Census#3332]

**Comment by Smit1610** [comment]
where is to be placed UI for light/dark mode feature ?

**Comment by Smit1610** [comment]
I have experience of dynamic UI change. Please assign to me .

**Comment by AniketP04** [comment]
I'm willing to work on this issue and collaborate with the maintainers. Please let me know how I can proceed.

**Comment by Dcode36** [comment]
@RitikJha93 Hey Assign this to me!!

**Comment by puran2003gupta** [comment]
hello can you please assign this to me...
