### ISSUE TITLE
Need help mantaining this?

### ISSUE THREAD

**Issue by m1guelpf** [Cutwell/Hacktoberfest-Census#848]
@Cutwell I can see there are more than 450 PR's open at the moment.
Need some help merging some? I can help!

**Comment by MichaelDeBoey** [comment]
I'd like to help as well, if needed 🙂

**Comment by shreyanshdwivedi** [comment]
@Cutwell if required I can help as well

**Comment by Cutwell** [comment]
I'm planning on writing an auto-merging script when I've got some spare time, so no help needed. To the best of my knowledge PR's don't need to be accepted to count towards Hacktoberfest, but do correct me if anyone knows more.

**Comment by MichaelDeBoey** [comment]
@Cutwell PR's indeed don't need to be accepted to count towards Hacktoberfest 🙂

**Comment by platy11** [comment]
@m1guelpf @MichaelDeBoey @shreyanshdwivedi If you're still interested in helping, see issue #1683.
